### PR TITLE
fix(downloader): fix .wav downloads and remove obsolete mp3 qualities.

### LINKED ISSUE #119: Error downloading most WAV files
When downloading tracks in .wav there is an error:

> 22:05:18 Error downloading Bensley - All Night: WrongResponseTypeException: Error downloading https://connect.monstercat.com/v2/release/4e3610b1-59d4-498b-be3c-1c7d36abdca9/track-download/4815dffc-60e8-450d-986a-d10fd618b994?format=wav: file type binary/octet-stream unexpected!

This does not happen to all files, but does happen to most.
image

### LINKED ISSUE #120: MP3 128 doesn't work anymore
Should be removed from the list of available downloads.

### PR DESCRIPTION
**Pull request by defvs**
e2da66a505a32db1a3811e10be5720ec69e0cef8 : fixes #120 
3700ee0542672b7a4c2696fb91d15e82e91ba26f : fixes #119

### CODE REVIEW

File: src/main/xerus/monstercat/downloader/TabDownloader.kt [hunk 1]
```diff
@@ -53,7 +53,7 @@ import java.util.concurrent.TimeUnit
 import kotlin.math.absoluteValue
 import xerus.ktutil.javafx.ui.controls.Type as SearchType
 
-private val qualities = arrayOf("mp3_128", "mp3_v2", "mp3_v0", "mp3_320", "flac", "wav")
```
Comment (xerus2000) [inline src/main/xerus/monstercat/downloader/TabDownloader.kt:56]: They removed MP3 variable bitrate? What the heck?

Comment (defvs) [reply src/main/xerus/monstercat/downloader/TabDownloader.kt:56]: yes. Only MP3_320, FLAC and WAV are available anymore. They used to redirect the other MP3 qualities but they don't anymore
